import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SideBar } from "./component/SideBar";

import SocialsLinks from "@/app/component/Socials";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-row items-start justify-start max-w-6xl mx-auto pt-16`}
      >
        <SideBar />
        <div className="pl-[200px] w-full">{children}</div>
        <SocialsLinks />
      </body>
    </html>
  );
}
